version: '3.9'
services:
  vehicle-service-db:
    image: postgres:16.1
    container_name: vehicle-service-db
    environment:
      POSTGRES_DB: vehicle-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - vehicle-service-network
networks:
  vehicle-service-network:
    name: vehicle-service-network
    driver: bridge

